[main]
  extraCommands = ["git push", "git push --tags"]
  serialize = "{version}-{banner}"
  tag = true
  version = "1.2.0"

[[operate]]
  location = "cmd/FileNotifier/main.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""